version: "3.7"

services:
  app:
    image: lscr.io/linuxserver/calibre-web:0.6.21
    restart: on-failure
    ports:
      - "${APP_PORT}:8083"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    volumes:
      - "${APP_DATA_DIR}/data/config:/config"
      - "${APP_DATA_DIR}/data/books:/books"
