version: "3.7"

services:
  app:
    image: portainer/portainer-ce:2.20.2
    restart: on-failure
    ports:
      - "${APP_PORT}:9443"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${APP_DATA_DIR}/data:/data"
    command: --ssl
